{
  "formatVersion": "1.1",
  "component": {
    "group": "be.kuleuven",
    "module": "CheckNeigboursInGrid",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "CheckNeigboursInGrid-1.0-SNAPSHOT.jar",
          "url": "CheckNeigboursInGrid-1.0-SNAPSHOT.jar",
          "size": 2104,
          "sha512": "bd5b92fdbe0c1c430786b6ae4d862cbb72262d52c1d729158e598866260923b1daee7f346307a710e418beecbbd391d79d5883cdabb56ee22298f0d523e3f5f4",
          "sha256": "e9577c11418f4acdb9483cb72b26f1d43da7c82599d4ae8be48da9f739e54512",
          "sha1": "540600a7085d8e7b0123e5c7ebb30d62e4669d20",
          "md5": "0353739df92dd7035c68354fc9445992"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "CheckNeigboursInGrid-1.0-SNAPSHOT.jar",
          "url": "CheckNeigboursInGrid-1.0-SNAPSHOT.jar",
          "size": 2104,
          "sha512": "bd5b92fdbe0c1c430786b6ae4d862cbb72262d52c1d729158e598866260923b1daee7f346307a710e418beecbbd391d79d5883cdabb56ee22298f0d523e3f5f4",
          "sha256": "e9577c11418f4acdb9483cb72b26f1d43da7c82599d4ae8be48da9f739e54512",
          "sha1": "540600a7085d8e7b0123e5c7ebb30d62e4669d20",
          "md5": "0353739df92dd7035c68354fc9445992"
        }
      ]
    }
  ]
}
