{
  "formatVersion": "1.1",
  "component": {
    "group": "be.kuleuven",
    "module": "CheckNeigboursInGrid",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "CheckNeigboursInGrid-1.0-SNAPSHOT.jar",
          "url": "CheckNeigboursInGrid-1.0-SNAPSHOT.jar",
          "size": 1923,
          "sha512": "603a3c6ec8194745a60a9426b1aa23894566f4ad567d464fe9824bb17962e5622c2aa03a62c1fbb29e0b40c95332b26bf83af5811138e2179fa0ace1144cbc90",
          "sha256": "a8f1e2206de4dfa01958e437010ba98c1891cd6092dc94f7e99fcc3f5d797d76",
          "sha1": "6c21af82e8180e73c1bcf75bf7dddb5f11861f3e",
          "md5": "8bd67fd168eb73e8c41470666b7256a8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "CheckNeigboursInGrid-1.0-SNAPSHOT.jar",
          "url": "CheckNeigboursInGrid-1.0-SNAPSHOT.jar",
          "size": 1923,
          "sha512": "603a3c6ec8194745a60a9426b1aa23894566f4ad567d464fe9824bb17962e5622c2aa03a62c1fbb29e0b40c95332b26bf83af5811138e2179fa0ace1144cbc90",
          "sha256": "a8f1e2206de4dfa01958e437010ba98c1891cd6092dc94f7e99fcc3f5d797d76",
          "sha1": "6c21af82e8180e73c1bcf75bf7dddb5f11861f3e",
          "md5": "8bd67fd168eb73e8c41470666b7256a8"
        }
      ]
    }
  ]
}
