{
  "formatVersion": "1.1",
  "component": {
    "group": "be.kuleuven",
    "module": "CheckNeigboursInGrid",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "CheckNeigboursInGrid-1.0-SNAPSHOT.jar",
          "url": "CheckNeigboursInGrid-1.0-SNAPSHOT.jar",
          "size": 1976,
          "sha512": "dc99f72d212de2fae6a84edbaba29b78101ab8516866331226def1d727d9eeb29ec2f6658081034a835b684e39aaa5957422e265a02e2f4929229f158a3448ba",
          "sha256": "c7d2a37fe3d7d9d1b557b14a72f903644e4d2e360a39108854e7c0b25dff205f",
          "sha1": "7b29538d94febeedcc2fc8a0ac9377b6c0d9fc5c",
          "md5": "f07f11944680c86bbad47da0776c248c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "CheckNeigboursInGrid-1.0-SNAPSHOT.jar",
          "url": "CheckNeigboursInGrid-1.0-SNAPSHOT.jar",
          "size": 1976,
          "sha512": "dc99f72d212de2fae6a84edbaba29b78101ab8516866331226def1d727d9eeb29ec2f6658081034a835b684e39aaa5957422e265a02e2f4929229f158a3448ba",
          "sha256": "c7d2a37fe3d7d9d1b557b14a72f903644e4d2e360a39108854e7c0b25dff205f",
          "sha1": "7b29538d94febeedcc2fc8a0ac9377b6c0d9fc5c",
          "md5": "f07f11944680c86bbad47da0776c248c"
        }
      ]
    }
  ]
}
