
name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:

    runs-on: windows-latest
    permissions:
      contents: read
    defaults:
      run:
        working-directory: ./CandycrushJavaFXstartProject/candycrush
      
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Test with Gradle Wrapper
      run: ./gradlew test
